- name: Configure lorad
  groups:
    - all
  tasks:
    - !shell
      name: Configuring Lorad
      cmd: conflex -ajo /etc/lorad/lorad.json /usr/share/lorad/boards/wifc-f923.json /usr/share/lorad/frequency_plans/sx1301/AS923-4.json
    - !sd_service
      name: Restart lorad
      service: lorad
      enabled: true
      restart: true

- name: Add chirpstack repository
  groups:
    - all

  tasks:
  - !external
    use: copycontent
    name: "Add chirpstack repository"
    params:
      dest: "/etc/apt/sources.list.d/chirpstack_4.list"
      content: |
          deb https://artifacts.chirpstack.io/packages/4.x/deb stable main
  - !external
    use: copycontent
    name: "Exclude chirpstack-mqtt-forwarder"
    params:
      dest: "/etc/apt/preferences.d/50-chirpstack-mqtt-forwarder"
      content: |
        Package: chirpstack-mqtt-forwarder
        Pin: origin artifacts.chirpstack.io
        Pin-Priority: -1
  - !shell
    name: "Add chirpstack key"
    cmd: curl -s "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1ce2afd36dbcca00" | gpg --dearmor > /etc/apt/trusted.gpg.d/chirpstack_4.gpg
  - !shell
    name: update repo
    cmd: apt update

- name: Install chirpstack
  groups:
    - all

  defaults:
     apt_packages:
        - chirpstack
        - postgresql
        - postgresql-client
        - postgresql-contrib
        - mosquitto
        - mosquitto-clients
        - redis
        - zram

  tasks:
     - !apt
       name: Install packages
       package: "{{ item }}"
       with:
          items: apt_packages
     - !shell
       name: Allow external gateway
       cmd: printf "\n[gateway]\n  allow_unknown_gateways=true\n" >> /etc/chirpstack/chirpstack.toml

- name: Setup postgresql for chirpstack
  groups:
    - all

  tasks:
    - !shell
      name: Init database
      cmd: su -l postgres -c "/usr/bin/initdb --pgdata='/var/lib/postgresql/data' --auth='trust'"
    - !sd_service
      name: Start posgres
      service: postgresql
      enabled: true
      restart: true
    - !external
      use: copycontent
      name: "Add chirpstack repository"
      params:
        dest: "/tmp/setup_postregsql.sh"
        content: |
          #!/bin/sh
          su - postgres -c "psql -c \" create role chirpstack with login password 'chirpstack' \" "
          su - postgres -c "psql -c \" create database chirpstack with owner chirpstack \" "
          su - postgres -c "psql -d chirpstack -c \" create extension pg_trgm \" "
    - !shell
      name: Create database for chirpstack
      cmd: sh /tmp/setup_postregsql.sh
    - !sd_service
      name: Start chirpstack
      service: chirpstack
      enabled: true
      restart: true
    - !shell
      name: Add local gateway
      cmd: sleep 2 && su - postgres -c "psql -d chirpstack -c \"  insert into gateway (gateway_id, tenant_id, created_at, updated_at, last_seen_at, name, description, latitude, longitude, altitude, stats_interval_secs, tls_certificate, tags, properties) values (bytea '\x$EUI64', (select id from tenant limit 1), now(), now(), null, 'local gateway', 'self', 0.0, 0.0, 0.0, 30, null, '{}', '{}')  \" "

- name: Allow http-alt connection
  groups:
    - all

  tasks:
    - !external
      use: copycontent
      name: "Open firewall for chirpstack"
      params:
        dest: "/etc/iptables/iptables.d/chirpstack.rules"
        content: |
          *filter
          -A INPUT -p tcp --dport http-alt -j ACCEPT
          COMMIT
    - !sd_service
      name: Reload firewall
      service: iptables
      enabled: true
      restart: true

- name: Setup a follower gateway
  groups:
    - all

  defaults:
    mqtt:
      topic: "as915_4"
      server: "localhost:1883"

  tasks:
    - !shell
      name: update repo
      cmd: apt update

    - !apt
      name: Install chirpstack-mqtt-forwarder
      package: chirpstack-mqtt-forwarder

    - !template
      name: Configure chirpstack-mqtt-forwarder
      src: /usr/share/chirpstack-mqtt-forwarder/template.hb
      dest: /etc/chirpstack-mqtt-forwarder/chirpstack-mqtt-forwarder.toml

    - !sd_service
      name: Restart chirpstack-mqtt-forwarder
      service: chirpstack-mqtt-forwarder
      enabled: true
      restart: true
- name: Allow mqtt to listen on local interface
  groups:
    - all

  tasks:
    - !shell
      name: allow include dir for mosquitto
      cmd: mkdir -p /etc/mosquitto/conf.d/ && echo "include_dir /etc/mosquitto/conf.d/" >> /etc/mosquitto/mosquitto.conf
    - !external
      use: copycontent
      name: add rule to listen on local interface
      params:
        dest: "/etc/mosquitto/conf.d/local.conf"
        content: |
          listener 1883 0.0.0.0
          allow_anonymous true
    - !sd_service
      name: Reload mosquitto
      service: mosquitto
      enabled: true
      restart: true
